BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[Question] (
    [id] INT NOT NULL IDENTITY(1,1),
    [title] NVARCHAR(1000) NOT NULL,
    [answer] NVARCHAR(1000),
    [view] INT NOT NULL CONSTRAINT [Question_view_df] DEFAULT 0,
    [createdAt] DATETIME2 NOT NULL CONSTRAINT [Question_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [Question_pkey] PRIMARY KEY CLUSTERED ([id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
